### ISSUE TITLE
Named export ignored by aegir, breaking latest version of ipfs-core

### ISSUE THREAD

**Issue by TheTrueRandom** [ipfs/js-datastore-core#110]
Named export [from the last commit](https://github.com/ipfs/js-datastore-core/commit/7a8f9ffb226c4940145637a6c881b835ce4886cb#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R9 ) is ignored by aegir and will result in `dist/esm/src/index.js` as `export * from './errors.js';`

This in return throws an error when importing datastore-core from ipfs 
`SyntaxError: The requested module 'datastore-core' does not provide an export named 'Errors'`

This causes the latest version of ipfs-core (0.15.4) to throw an error when importing
`import * as IPFS from 'ipfs-core'` -> `SyntaxError: The requested module 'datastore-core' does not provide an export named 'Errors'`

**Comment by taylorhulsmans** [comment]
Ran into this today as well from vite react typescript.  I pushed a minimal reproduction of the issue here https://github.com/taylorhulsmans/datastore-core-110-react-vite-example/tree/master

**Comment by achingbrain** [comment]
This module has been converted to typescript so the types are no longer generated from jsdoc and should be more compatible.

Please re-open if you're still seeing this issue.
