### ISSUE TITLE
CI for windows

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-datastore-core#5]
Could we also run the build on `appveyor`?

**Comment by dignifiedquire** [comment]
@richardschneider I have added appveyor for

- https://ci.appveyor.com/project/dignifiedquire/js-datastore
- https://ci.appveyor.com/project/dignifiedquire/interface-datastore
- https://ci.appveyor.com/project/dignifiedquire/js-datastore-core
- https://ci.appveyor.com/project/dignifiedquire/js-datastore-fs
- https://ci.appveyor.com/project/dignifiedquire/js-datastore-level

could you take care of PRing the appropriate badges for the readmes please?

**Comment by richardschneider** [comment]
I can't do it because I need access to the [project badge settings](https://ci.appveyor.com/project/dignifiedquire/interface-datastore/settings/badges). This page has the badge url.

**Comment by diasdavid** [comment]
Being added with https://github.com/ipfs/js-datastore-core/pull/3

Thanks @dignifiedquire for enabling it :)
